name: Lint Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Run lint check
      working-directory: ./nextjs-app
      run: |
        npm ci
        npm run lint
